// Auth
export const START_AUTH_ACTION = 'START_AUTH_ACTION';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

// Countries
export const START_COUNTRY_ACTION = 'START_COUNTRY_ACTION';
export const FAILED_COUNTRY_ACTION = 'FAILED_COUNTRY_ACTION';
export const CREATE_COUNTRY = 'CREATE_COUNTRY';
export const CREATE_COUNTRY_SUCCESS = 'CREATE_COUNTRY_SUCCESS';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const SELECT_COUNTRY = 'SELECT_COUNTRY';
export const SEARCH_COUNTRY = 'SEARCH_COUNTRY';
export const UPDATE_COUNTRY = 'UPDATE_COUNTRY';
export const UPDATE_COUNTRY_SUCCESS = 'UPDATE_COUNTRY_SUCCESS';
export const DELETE_COUNTRY = 'DELETE_COUNTRY';
export const DELETE_COUNTRY_DATA = 'DELETE_COUNTRY_DATA';
export const DELETE_COUNTRY_SUCCESS = 'DELETE_COUNTRY_SUCCESS';

// Demo
export const START_DEMO_DATA_ACTION = 'START_DEMO_DATA_ACTION';
export const FAILED_DEMO_DATA_ACTION = 'FAILED_DEMO_DATA_ACTION';
export const CREATE_DEMO_DATA = 'CREATE_DEMO_DATA';
export const CREATE_DEMO_DATA_SUCCESS = 'CREATE_DEMO_DATA_SUCCESS';
export const GET_DEMO_DATA = 'GET_DEMO_DATA';
export const GET_DEMO_DATA_SUCCESS = 'GET_DEMO_DATA_SUCCESS';
export const GET_ALL_DEMO_DATA = 'GET_ALL_DEMO_DATA';
export const GET_ALL_DEMO_DATA_SUCCESS = 'GET_ALL_DEMO_DATA_SUCCESS';
export const SELECT_DEMO_DATA = 'SELECT_DEMO_DATA';
export const SEARCH_DEMO_DATA = 'SEARCH_DEMO_DATA';
export const UPDATE_DEMO_DATA = 'UPDATE_DEMO_DATA';
export const UPDATE_DEMO_DATA_SUCCESS = 'UPDATE_DEMO_DATA_SUCCESS';
export const DELETE_DEMO_DATA = 'DELETE_DEMO_DATA';
export const DELETE_DEMO_DATA_SUCCESS = 'DELETE_DEMO_DATA_SUCCESS';

// Payments
export const START_PAYMENT_ACTION = 'START_PAYMENT_ACTION';
export const FAILED_PAYMENT_ACTION = 'FAILED_PAYMENT_ACTION';
export const CREATE_PAYMENT = 'CREATE_PAYMENT';
export const CREATE_PAYMENT_SUCCESS = 'CREATE_PAYMENT_SUCCESS';
export const GET_PAYMENTS = 'GET_PAYMENTS';
export const GET_PAYMENTS_SUCCESS = 'GET_PAYMENTS_SUCCESS';
export const SELECT_PAYMENT = 'SELECT_PAYMENT';
export const SEARCH_PAYMENT = 'SEARCH_PAYMENT';
export const UPDATE_PAYMENT = 'UPDATE_PAYMENT';
export const UPDATE_PAYMENT_SUCCESS = 'UPDATE_PAYMENT_SUCCESS';
export const DELETE_PAYMENT = 'DELETE_PAYMENT';
export const DELETE_PAYMENT_DATA = 'DELETE_PAYMENT_DATA';
export const DELETE_PAYMENT_SUCCESS = 'DELETE_PAYMENT_SUCCESS';

// Users
export const START_USER_ACTION = 'START_USER_ACTION';
export const FAILED_USER_ACTION = 'FAILED_USER_ACTION';
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const SELECT_USER = 'SELECT_USER';
export const SEARCH_USER = 'SEARCH_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_DATA = 'DELETE_USER_DATA';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

// Rol
export const START_ROL_ACTION = 'START_ROL_ACTION';
export const FAILED_ROL_ACTION = 'FAILED_ROL_ACTION';
export const CREATE_ROL = 'CREATE_ROL';
export const CREATE_ROL_SUCCESS = 'CREATE_USER_SUCCESS';
export const GET_ROLES = 'GET_ROLES';
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS';

// Notifications
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
